"""
Abstract base generator. Every AI document generator inherits from this class.

CIP compliance is enforced here — subclasses must not call Claude directly
without going through run(), which handles begin/complete_decision and graph
registration automatically.
"""

from __future__ import annotations

import json
import re
from abc import ABC, abstractmethod
from datetime import UTC, datetime
import anthropic
from anthropic.types import TextBlock
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models.artifact import Artifact, ArtifactType
from app.models.generation import GenerationJob, GenerationJobStatus
from app.models.graph import GraphEdgeType, GraphNodeType
from app.models.user import User
from app.repositories.generation_repository import GenerationRepository
from app.models.study import Study
from app.repositories.study_repository import StudyRepository
from app.services.artifact_service import ArtifactService
from app.services.context_graph_service import ContextGraphService
from app.services.intelligence_service import AIDecisionService, DataLineageService


class BaseGenerator(ABC):
    """
    Base class for all AI artifact generators.

    Subclasses implement _build_content() to call Claude and return a
    structured dict. This base class handles all CIP mandatory plumbing:
    - begin_decision() / complete_decision()
    - DRAFT artifact creation
    - Graph node registration (ARTIFACT node)
    - GENERATED_FROM edge (artifact → study)
    - Artifact lineage record
    - Job status lifecycle (RUNNING → COMPLETED / FAILED)
    """

    ARTIFACT_TYPE: ArtifactType
    AGENT_NAME: str

    def __init__(self, db: AsyncSession) -> None:
        self._db = db
        settings = get_settings()
        self._client = anthropic.AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)
        self._artifact_svc = ArtifactService(db)
        self._ai_decision_svc = AIDecisionService(db)
        self._graph_svc = ContextGraphService(db)
        self._lineage_svc = DataLineageService(db)
        self._study_repo = StudyRepository(db)
        self._gen_repo = GenerationRepository(db)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def run(self, job: GenerationJob, actor: User) -> None:
        """
        Execute the generation job end-to-end.

        Marks the job RUNNING, calls _build_content(), creates the DRAFT
        artifact, registers graph nodes, and marks the job COMPLETED.
        On any exception the job is marked FAILED with the error message.
        """
        await self._mark_running(job)

        try:
            study = await self._study_repo.get(job.study_id, job.organization_id)

            # CIP: log decision before any AI inference
            decision = await self._ai_decision_svc.begin_decision(
                organization_id=job.organization_id,
                agent_name=self.AGENT_NAME,
                decision_type="ARTIFACT_GENERATION",
                study_id=job.study_id,
                model_id=job.model_id,
                input_context=job.input_context,
            )

            content = await self._build_content(
                job=job, study=study, model_id=job.model_id
            )

            # Create DRAFT artifact
            artifact = await self._artifact_svc.create_artifact(
                organization_id=job.organization_id,
                study_id=job.study_id,
                user=actor,
                artifact_type=self.ARTIFACT_TYPE,
                name=self._artifact_name(study.name),
                description=f"AI-generated {self.ARTIFACT_TYPE.value} — requires review",
                content=content,
                change_summary=f"Generated by {self.AGENT_NAME} (model: {job.model_id})",
            )

            await self._register_generation_graph(
                job=job,
                study=study,
                artifact=artifact,
                actor=actor,
                decision=decision,
            )

            # CIP: complete decision
            await self._ai_decision_svc.complete_decision(
                decision=decision,
                output={
                    "artifact_id": str(artifact.id),
                    "artifact_type": self.ARTIFACT_TYPE.value,
                },
                reasoning=f"Generated {self.ARTIFACT_TYPE.value} document for study '{study.name}'",
                confidence=0.9,
                output_artifact_ids=[artifact.id],
            )

            await self._mark_completed(job, artifact)

        except Exception as exc:
            await self._mark_failed(job, str(exc))
            raise

    # ------------------------------------------------------------------
    # Subclass contract
    # ------------------------------------------------------------------

    @abstractmethod
    async def _build_content(
        self,
        job: GenerationJob,
        study: Study,
        model_id: str,
    ) -> dict:
        """
        Call the Claude API and return structured content.

        Must return a dict that can be stored as the artifact's content JSON.
        Use _call_claude() to make the API call.
        """
        ...

    @abstractmethod
    def _artifact_name(self, study_name: str) -> str:
        """Return the artifact name string."""
        ...

    # ------------------------------------------------------------------
    # Helpers available to subclasses
    # ------------------------------------------------------------------

    async def _call_claude(
        self,
        system_prompt: str,
        user_prompt: str,
        model_id: str,
        max_tokens: int = 4096,
    ) -> str:
        """Make a Claude API call and return the text response."""
        response = await self._client.messages.create(
            model=model_id,
            max_tokens=max_tokens,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        block = response.content[0]
        return block.text if isinstance(block, TextBlock) else ""

    def _format_brief_for_prompt(self, job: GenerationJob) -> str:
        """Return Study Brief JSON block when generation was triggered from a brief."""
        ctx = job.input_context or {}
        brief_content = ctx.get("brief_content")
        if not brief_content:
            return ""
        return (
            "\n\nCompiled Study Brief (primary source of truth — use all sections below):\n"
            f"{json.dumps(brief_content, indent=2)}\n"
        )

    async def _register_generation_graph(
        self,
        job: GenerationJob,
        study: Study,
        artifact: Artifact,
        actor: User,
        decision: object,
    ) -> None:
        """Register all mandatory CIP graph nodes and edges for a generation job."""
        from app.models.intelligence import AIDecision

        assert isinstance(decision, AIDecision)

        art_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.ARTIFACT,
            external_id=artifact.id,
            external_type="artifact",
            label=artifact.name,
            study_id=job.study_id,
            description=artifact.description,
            properties={
                "artifact_type": self.ARTIFACT_TYPE.value,
                "status": "DRAFT",
            },
            actor_agent_id=self.AGENT_NAME,
        )

        study_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.STUDY,
            external_id=study.id,
            external_type="study",
            label=study.name,
            study_id=study.id,
            actor_agent_id=self.AGENT_NAME,
        )

        # Artifact belongs_to Study
        await self._graph_svc.create_relationship(
            organization_id=job.organization_id,
            source_node_id=art_node.id,
            target_node_id=study_node.id,
            edge_type=GraphEdgeType.PART_OF,
            study_id=job.study_id,
            actor_agent_id=self.AGENT_NAME,
        )

        # ArtifactVersion belongs_to Artifact
        if artifact.current_version_id:
            version_node, _ = await self._graph_svc.register_domain_record(
                organization_id=job.organization_id,
                node_type=GraphNodeType.ARTIFACT,
                external_id=artifact.current_version_id,
                external_type="artifact_version",
                label=f"{artifact.name} v{artifact.current_version_number}",
                study_id=job.study_id,
                properties={"version_number": artifact.current_version_number},
                actor_agent_id=self.AGENT_NAME,
            )
            await self._graph_svc.create_relationship(
                organization_id=job.organization_id,
                source_node_id=version_node.id,
                target_node_id=art_node.id,
                edge_type=GraphEdgeType.PART_OF,
                study_id=job.study_id,
                actor_agent_id=self.AGENT_NAME,
            )

        # AIDecision created_by User (user triggered generation)
        decision_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.AI_DECISION,
            external_id=decision.id,
            external_type="ai_decision",
            label=f"{self.AGENT_NAME} decision",
            study_id=job.study_id,
            actor_agent_id=self.AGENT_NAME,
        )
        user_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.USER,
            external_id=actor.id,
            external_type="user",
            label=actor.email,
            study_id=job.study_id,
            actor=actor,
        )
        await self._graph_svc.create_relationship(
            organization_id=job.organization_id,
            source_node_id=decision_node.id,
            target_node_id=user_node.id,
            edge_type=GraphEdgeType.CREATED_BY,
            study_id=job.study_id,
            actor=actor,
        )

        # Artifact created_by AIDecision
        await self._graph_svc.create_relationship(
            organization_id=job.organization_id,
            source_node_id=art_node.id,
            target_node_id=decision_node.id,
            edge_type=GraphEdgeType.CREATED_BY,
            study_id=job.study_id,
            is_ai_generated=True,
            ai_decision_id=decision.id,
            confidence=0.9,
            actor_agent_id=self.AGENT_NAME,
        )

        # Protocol/ICF generated_from StudyBrief when triggered from brief
        ctx = job.input_context or {}
        brief_id = ctx.get("brief_id")
        derivation_notes = f"Generated by {self.AGENT_NAME} from study context"
        if brief_id:
            brief_node, _ = await self._graph_svc.register_domain_record(
                organization_id=job.organization_id,
                node_type=GraphNodeType.STUDY_BRIEF,
                external_id=UUID(str(brief_id)),
                external_type="study_brief",
                label="Study Brief",
                study_id=job.study_id,
                actor_agent_id=self.AGENT_NAME,
            )
            await self._graph_svc.create_relationship(
                organization_id=job.organization_id,
                source_node_id=art_node.id,
                target_node_id=brief_node.id,
                edge_type=GraphEdgeType.GENERATED_FROM,
                study_id=job.study_id,
                is_ai_generated=True,
                ai_decision_id=decision.id,
                confidence=0.9,
                actor_agent_id=self.AGENT_NAME,
            )
            derivation_notes = (
                f"Generated by {self.AGENT_NAME} from compiled Study Brief"
            )
        else:
            await self._graph_svc.create_relationship(
                organization_id=job.organization_id,
                source_node_id=art_node.id,
                target_node_id=study_node.id,
                edge_type=GraphEdgeType.GENERATED_FROM,
                study_id=job.study_id,
                is_ai_generated=True,
                ai_decision_id=decision.id,
                confidence=0.9,
                actor_agent_id=self.AGENT_NAME,
            )

        await self._lineage_svc.record_artifact_lineage(
            organization_id=job.organization_id,
            source_artifact_id=artifact.id,
            target_artifact_id=artifact.id,
            relationship_type="AI_GENERATED",
            study_id=job.study_id,
            source_version_id=artifact.current_version_id,
            target_version_id=artifact.current_version_id,
            derivation_notes=derivation_notes,
            is_ai_generated=True,
            ai_decision_id=decision.id,
            created_by=actor,
        )

    @staticmethod
    def _parse_json_response(text: str) -> dict:
        """
        Extract and parse JSON from a Claude response.

        Handles both bare JSON and JSON wrapped in markdown code fences.
        Raises ValueError if no valid JSON is found.
        """
        # Strip markdown fences
        cleaned = re.sub(r"^```(?:json)?\s*", "", text.strip(), flags=re.MULTILINE)
        cleaned = re.sub(r"\s*```$", "", cleaned.strip(), flags=re.MULTILINE)
        try:
            return json.loads(cleaned.strip())
        except json.JSONDecodeError as e:
            # Try finding the first {...} block
            match = re.search(r"\{.*\}", cleaned, re.DOTALL)
            if match:
                return json.loads(match.group())
            raise ValueError(f"Could not parse JSON from response: {e}") from e

    # ------------------------------------------------------------------
    # Job status helpers
    # ------------------------------------------------------------------

    async def _mark_running(self, job: GenerationJob) -> None:
        job.status = GenerationJobStatus.RUNNING
        job.started_at = datetime.now(UTC)
        await self._db.flush()

    async def _mark_completed(self, job: GenerationJob, artifact: Artifact) -> None:
        job.status = GenerationJobStatus.COMPLETED
        job.output_artifact_id = artifact.id
        job.completed_at = datetime.now(UTC)
        await self._db.flush()

    async def _mark_failed(self, job: GenerationJob, error: str) -> None:
        job.status = GenerationJobStatus.FAILED
        job.error_message = error[:2000]  # truncate for DB column
        job.completed_at = datetime.now(UTC)
        try:
            await self._db.flush()
        except Exception:
            pass
