"""
Abstract base generator. Every AI document generator inherits from this class.

CIP compliance is enforced here — subclasses must not call Claude directly
without going through run(), which handles begin/complete_decision and graph
registration automatically.
"""

from __future__ import annotations

import asyncio
import json
import re
from abc import ABC, abstractmethod
from datetime import UTC, datetime
from uuid import UUID
import anthropic
from anthropic.types import TextBlock
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.exceptions import GenerationCancelledError
from app.models.artifact import Artifact, ArtifactType
from app.models.generation import GenerationJob, GenerationJobStatus
from app.models.graph import GraphEdgeType, GraphNodeType
from app.models.user import User
from app.repositories.generation_repository import GenerationRepository
from app.models.study import Study
from app.repositories.study_repository import StudyRepository
from app.services.artifact_service import ArtifactService
from app.services.context_graph_service import ContextGraphService
from app.services.generators.reasoning_builder import build_artifact_reasoning
from app.services.intelligence_service import AIDecisionService, DataLineageService

_MODEL_ALIASES: dict[str, str] = {
    "claude-sonnet": "claude-sonnet-4-6",
    "claude-opus": "claude-opus-4-7",
    "claude-haiku": "claude-haiku-4-5-20251001",
}


class BaseGenerator(ABC):
    """
    Base class for all AI artifact generators.

    Subclasses implement _build_content() to call Claude and return a
    structured dict. This base class handles all CIP mandatory plumbing:
    - begin_decision() / complete_decision()
    - DRAFT artifact creation
    - Graph node registration (ARTIFACT node)
    - GENERATED_FROM edge (artifact → study)
    - Artifact lineage record
    - Job status lifecycle (RUNNING → COMPLETED / FAILED)
    """

    ARTIFACT_TYPE: ArtifactType
    AGENT_NAME: str

    def __init__(self, db: AsyncSession) -> None:
        self._db = db
        settings = get_settings()
        self._client = anthropic.AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)
        self._artifact_svc = ArtifactService(db)
        self._ai_decision_svc = AIDecisionService(db)
        self._graph_svc = ContextGraphService(db)
        self._lineage_svc = DataLineageService(db)
        self._study_repo = StudyRepository(db)
        self._gen_repo = GenerationRepository(db)
        self._settings = settings

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def run(self, job: GenerationJob, actor: User) -> None:
        """
        Execute the generation job end-to-end.

        Marks the job RUNNING, calls _build_content(), creates the DRAFT
        artifact, registers graph nodes, and marks the job COMPLETED.
        On any exception the job is marked FAILED with the error message.
        """
        try:
            if not self._settings.ANTHROPIC_API_KEY:
                raise ValueError(
                    "ANTHROPIC_API_KEY is not configured. "
                    "Set it in the environment to run AI generation."
                )

            await self._ensure_not_cancelled(job)
            await self._mark_running(job)
            await self._db.commit()
            await self._ensure_not_cancelled(job)

            study = await self._study_repo.get(job.study_id, job.organization_id)

            # CIP: log decision before any AI inference
            decision = await self._ai_decision_svc.begin_decision(
                organization_id=job.organization_id,
                agent_name=self.AGENT_NAME,
                decision_type="ARTIFACT_GENERATION",
                study_id=job.study_id,
                model_id=job.model_id,
                input_context=job.input_context,
            )

            content = await self._build_content(
                job=job, study=study, model_id=job.model_id
            )
            await self._ensure_not_cancelled(job)

            # Create DRAFT artifact
            artifact = await self._artifact_svc.create_artifact(
                organization_id=job.organization_id,
                study_id=job.study_id,
                user=actor,
                artifact_type=self.ARTIFACT_TYPE,
                name=self._artifact_name(study.name),
                description=f"AI-generated {self.ARTIFACT_TYPE.value} — requires review",
                content=content,
                change_summary=f"Generated by {self.AGENT_NAME} (model: {job.model_id})",
            )

            art_node_id = await self._register_generation_graph(
                job=job,
                study=study,
                artifact=artifact,
                actor=actor,
                decision=decision,
            )

            await self._register_additional_graph(
                job=job,
                study=study,
                artifact=artifact,
                actor=actor,
                decision=decision,
                art_node_id=art_node_id,
                content=content,
            )

            reasoning = self._build_detailed_reasoning(
                job=job, study=study, content=content
            )

            # CIP: complete decision
            await self._ai_decision_svc.complete_decision(
                decision=decision,
                output={
                    "artifact_id": str(artifact.id),
                    "artifact_type": self.ARTIFACT_TYPE.value,
                    "reasoning_summary": reasoning.split("\n\n")[0][:500],
                },
                reasoning=reasoning,
                confidence=0.9,
                output_artifact_ids=[artifact.id],
                graph_node_id=art_node_id,
            )

            await self._mark_completed(job, artifact)

        except GenerationCancelledError:
            await self._mark_cancelled(job)
            await self._db.commit()
        except (asyncio.TimeoutError, TimeoutError) as exc:
            try:
                await self._ensure_not_cancelled(job)
                await self._mark_failed(
                    job,
                    str(exc) or "Claude API call timed out",
                )
            except GenerationCancelledError:
                await self._mark_cancelled(job)
            await self._db.commit()
        except Exception as exc:
            await self._mark_failed(job, str(exc))
            await self._db.commit()

    # ------------------------------------------------------------------
    # Subclass contract
    # ------------------------------------------------------------------

    @abstractmethod
    async def _build_content(
        self,
        job: GenerationJob,
        study: Study,
        model_id: str,
    ) -> dict:
        """
        Call the Claude API and return structured content.

        Must return a dict that can be stored as the artifact's content JSON.
        Use _call_claude() to make the API call.
        """
        ...

    @abstractmethod
    def _artifact_name(self, study_name: str) -> str:
        """Return the artifact name string."""
        ...

    # ------------------------------------------------------------------
    # Helpers available to subclasses
    # ------------------------------------------------------------------

    def _normalize_model_id(self, model_id: str) -> str:
        """Map legacy shorthand model names to current Anthropic model IDs."""
        return _MODEL_ALIASES.get(model_id, model_id)

    #: Hard ceiling on continuation rounds for a single generation. Each round
    #: is one additional API call resuming a truncated response. This bounds
    #: cost/latency and guarantees the loop terminates.
    MAX_CONTINUATION_ROUNDS: int = 4

    #: Instruction used to resume a truncated response. We cannot prefill the
    #: assistant turn — current Claude models reject a conversation ending in an
    #: assistant message — so the partial output is sent back as a prior turn and
    #: the model is asked to emit only the remainder, which we concatenate.
    _CONTINUE_INSTRUCTION = (
        "Your previous response was cut off because it hit the length limit. "
        "Continue the JSON output from exactly where you stopped. Output only "
        "the remaining characters — do not repeat any prior content and do not "
        "wrap the output in markdown fences."
    )

    async def _call_claude(
        self,
        system_prompt: str,
        user_prompt: str,
        model_id: str,
        max_tokens: int = 8192,
    ) -> str:
        """Make a Claude API call and return the full text response.

        When the model hits the ``max_tokens`` budget for a single response,
        the JSON is truncated mid-structure and cannot be parsed. To prevent
        that, this method detects ``stop_reason == "max_tokens"`` and resumes
        the generation: the partial output is replayed as an assistant turn and
        the model is asked to continue (see ``_CONTINUE_INSTRUCTION``). The
        pieces are concatenated until the model completes (``stop_reason`` other
        than ``"max_tokens"``) or the continuation budget is exhausted.

        Raises:
            TimeoutError: if any single API call exceeds the job timeout.
            ValueError: if the output is still truncated after
                ``MAX_CONTINUATION_ROUNDS`` continuations — surfaced loudly so
                the caller fails instead of parsing a partial artifact.
        """
        resolved_model = self._normalize_model_id(model_id)
        accumulated = ""

        for round_index in range(self.MAX_CONTINUATION_ROUNDS + 1):
            # First round sends only the user prompt; subsequent rounds replay
            # the text so far as an assistant turn and ask the model to continue
            # (the conversation must end with a user message).
            if accumulated:
                messages = [
                    {"role": "user", "content": user_prompt},
                    {"role": "assistant", "content": accumulated},
                    {"role": "user", "content": self._CONTINUE_INSTRUCTION},
                ]
            else:
                messages = [{"role": "user", "content": user_prompt}]

            try:
                response = await asyncio.wait_for(
                    self._client.messages.create(
                        model=resolved_model,
                        max_tokens=max_tokens,
                        system=system_prompt,
                        messages=messages,
                    ),
                    timeout=self._settings.AI_JOB_TIMEOUT_SECONDS,
                )
            except asyncio.TimeoutError as exc:
                raise TimeoutError(
                    f"Claude API call timed out after "
                    f"{self._settings.AI_JOB_TIMEOUT_SECONDS}s "
                    f"(model: {resolved_model})"
                ) from exc

            block = response.content[0] if response.content else None
            chunk = block.text if isinstance(block, TextBlock) else ""
            accumulated += chunk

            if getattr(response, "stop_reason", None) != "max_tokens":
                return accumulated

            # Truncated: trim trailing whitespace (the API rejects an assistant
            # prefill ending in whitespace) and continue from there.
            accumulated = accumulated.rstrip()

        raise ValueError(
            f"Model output still truncated after "
            f"{self.MAX_CONTINUATION_ROUNDS} continuation rounds "
            f"({len(accumulated)} chars accumulated, model: {resolved_model}). "
            f"Increase max_tokens or narrow the generation scope."
        )

    async def _register_additional_graph(
        self,
        job: GenerationJob,
        study: Study,
        artifact: Artifact,
        actor: User,
        decision: object,
        art_node_id: UUID,
        content: dict,
    ) -> None:
        """Optional hook for subclasses to register extra context graph nodes."""
        return None

    def _build_detailed_reasoning(
        self,
        job: GenerationJob,
        study: Study,
        content: dict,
    ) -> str:
        """Build audit-grade reasoning from Study Brief intake answers."""
        ctx = job.input_context or {}
        brief_content = ctx.get("brief_content")
        if isinstance(brief_content, dict):
            brief = brief_content
        else:
            brief = None
        return build_artifact_reasoning(
            artifact_type=self.ARTIFACT_TYPE,
            study=study,
            brief_content=brief,
            content=content,
        )

    def _format_brief_for_prompt(self, job: GenerationJob) -> str:
        """Return Study Brief JSON block when generation was triggered from a brief."""
        ctx = job.input_context or {}
        brief_content = ctx.get("brief_content")
        if not brief_content:
            return ""
        return (
            "\n\nCompiled Study Brief (primary source of truth — use all sections below):\n"
            f"{json.dumps(brief_content, indent=2)}\n"
        )

    async def _register_generation_graph(
        self,
        job: GenerationJob,
        study: Study,
        artifact: Artifact,
        actor: User,
        decision: object,
    ) -> UUID:
        """Register all mandatory CIP graph nodes and edges for a generation job."""
        from app.models.intelligence import AIDecision

        assert isinstance(decision, AIDecision)

        art_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=self._primary_graph_node_type(),
            external_id=artifact.id,
            external_type="artifact",
            label=artifact.name,
            study_id=job.study_id,
            description=artifact.description,
            properties={
                "artifact_type": self.ARTIFACT_TYPE.value,
                "status": "DRAFT",
            },
            actor_agent_id=self.AGENT_NAME,
        )

        study_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.STUDY,
            external_id=study.id,
            external_type="study",
            label=study.name,
            study_id=study.id,
            actor_agent_id=self.AGENT_NAME,
        )

        # Artifact belongs_to Study
        await self._graph_svc.create_relationship(
            organization_id=job.organization_id,
            source_node_id=art_node.id,
            target_node_id=study_node.id,
            edge_type=GraphEdgeType.PART_OF,
            study_id=job.study_id,
            actor_agent_id=self.AGENT_NAME,
        )

        # ArtifactVersion belongs_to Artifact
        if artifact.current_version_id:
            version_node, _ = await self._graph_svc.register_domain_record(
                organization_id=job.organization_id,
                node_type=GraphNodeType.ARTIFACT,
                external_id=artifact.current_version_id,
                external_type="artifact_version",
                label=f"{artifact.name} v{artifact.current_version_number}",
                study_id=job.study_id,
                properties={"version_number": artifact.current_version_number},
                actor_agent_id=self.AGENT_NAME,
            )
            await self._graph_svc.create_relationship(
                organization_id=job.organization_id,
                source_node_id=version_node.id,
                target_node_id=art_node.id,
                edge_type=GraphEdgeType.PART_OF,
                study_id=job.study_id,
                actor_agent_id=self.AGENT_NAME,
            )

        # AIDecision created_by User (user triggered generation)
        decision_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.AI_DECISION,
            external_id=decision.id,
            external_type="ai_decision",
            label=f"{self.AGENT_NAME} decision",
            study_id=job.study_id,
            actor_agent_id=self.AGENT_NAME,
        )
        user_node, _ = await self._graph_svc.register_domain_record(
            organization_id=job.organization_id,
            node_type=GraphNodeType.USER,
            external_id=actor.id,
            external_type="user",
            label=actor.email,
            study_id=job.study_id,
            actor=actor,
        )
        await self._graph_svc.create_relationship(
            organization_id=job.organization_id,
            source_node_id=decision_node.id,
            target_node_id=user_node.id,
            edge_type=GraphEdgeType.CREATED_BY,
            study_id=job.study_id,
            actor=actor,
        )

        # Artifact created_by AIDecision
        await self._graph_svc.create_relationship(
            organization_id=job.organization_id,
            source_node_id=art_node.id,
            target_node_id=decision_node.id,
            edge_type=GraphEdgeType.CREATED_BY,
            study_id=job.study_id,
            is_ai_generated=True,
            ai_decision_id=decision.id,
            confidence=0.9,
            actor_agent_id=self.AGENT_NAME,
        )

        # Protocol/ICF generated_from StudyBrief when triggered from brief
        ctx = job.input_context or {}
        brief_id = ctx.get("brief_id")
        derivation_notes = f"Generated by {self.AGENT_NAME} from study context"
        if brief_id:
            brief_node, _ = await self._graph_svc.register_domain_record(
                organization_id=job.organization_id,
                node_type=GraphNodeType.STUDY_BRIEF,
                external_id=UUID(str(brief_id)),
                external_type="study_brief",
                label="Study Brief",
                study_id=job.study_id,
                actor_agent_id=self.AGENT_NAME,
            )
            await self._graph_svc.create_relationship(
                organization_id=job.organization_id,
                source_node_id=art_node.id,
                target_node_id=brief_node.id,
                edge_type=GraphEdgeType.GENERATED_FROM,
                study_id=job.study_id,
                is_ai_generated=True,
                ai_decision_id=decision.id,
                confidence=0.9,
                actor_agent_id=self.AGENT_NAME,
            )
            derivation_notes = (
                f"Generated by {self.AGENT_NAME} from compiled Study Brief"
            )
        else:
            await self._graph_svc.create_relationship(
                organization_id=job.organization_id,
                source_node_id=art_node.id,
                target_node_id=study_node.id,
                edge_type=GraphEdgeType.GENERATED_FROM,
                study_id=job.study_id,
                is_ai_generated=True,
                ai_decision_id=decision.id,
                confidence=0.9,
                actor_agent_id=self.AGENT_NAME,
            )

        await self._lineage_svc.record_artifact_lineage(
            organization_id=job.organization_id,
            source_artifact_id=artifact.id,
            target_artifact_id=artifact.id,
            relationship_type="AI_GENERATED",
            study_id=job.study_id,
            source_version_id=artifact.current_version_id,
            target_version_id=artifact.current_version_id,
            derivation_notes=derivation_notes,
            is_ai_generated=True,
            ai_decision_id=decision.id,
            created_by=actor,
        )

        event_type = self._graph_event_type()
        if event_type:
            await self._graph_svc.emit_event(
                organization_id=job.organization_id,
                study_id=job.study_id,
                event_type=event_type,
                actor_agent_id=self.AGENT_NAME,
                ai_decision_id=decision.id,
                node_id=art_node.id,
                payload={
                    "artifact_id": str(artifact.id),
                    "artifact_type": self.ARTIFACT_TYPE.value,
                    "artifact_name": artifact.name,
                },
            )

        return art_node.id

    def _primary_graph_node_type(self) -> GraphNodeType:
        """Map artifact type to the most specific context graph node type."""
        from app.services.artifact_service import artifact_graph_node_type

        return artifact_graph_node_type(self.ARTIFACT_TYPE)

    def _graph_event_type(self) -> str | None:
        """Context graph event emitted when generation completes."""
        mapping: dict[ArtifactType, str] = {
            ArtifactType.PROTOCOL: "PROTOCOL_GENERATED",
            ArtifactType.ICF: "ICF_GENERATED",
            ArtifactType.SAP: "SAP_GENERATED",
            ArtifactType.EDC_CRF: "EDC_SPECIFICATION_GENERATED",
        }
        return mapping.get(self.ARTIFACT_TYPE, "ARTIFACT_GENERATED")

    @staticmethod
    def _sanitize_json_text(text: str) -> str:
        """Strip fences and fix common JSON issues from LLM output."""
        cleaned = re.sub(r"^```(?:json)?\s*", "", text.strip(), flags=re.MULTILINE)
        cleaned = re.sub(r"\s*```$", "", cleaned.strip(), flags=re.MULTILINE)
        cleaned = cleaned.strip()
        # Trailing commas before closing braces (invalid in strict JSON)
        cleaned = re.sub(r",(\s*[}\]])", r"\1", cleaned)
        return cleaned

    @staticmethod
    def _close_truncated_json(text: str) -> str:
        """Best-effort close JSON truncated mid-stream by the model."""
        depth_obj = 0
        depth_arr = 0
        in_string = False
        escape = False
        for ch in text:
            if escape:
                escape = False
                continue
            if ch == "\\" and in_string:
                escape = True
                continue
            if ch == '"':
                in_string = not in_string
                continue
            if in_string:
                continue
            if ch == "{":
                depth_obj += 1
            elif ch == "}":
                depth_obj -= 1
            elif ch == "[":
                depth_arr += 1
            elif ch == "]":
                depth_arr -= 1
        if in_string:
            text += '"'
        suffix = "]" * max(depth_arr, 0) + "}" * max(depth_obj, 0)
        return text + suffix if suffix else text

    @classmethod
    def _parse_json_response(cls, text: str) -> dict:
        """
        Extract and parse JSON from a Claude response.

        Handles markdown fences, trailing commas, and truncated output.
        Raises ValueError if no valid JSON is found.
        """
        cleaned = cls._sanitize_json_text(text)
        candidates = [cleaned]
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if match:
            candidates.append(match.group())
        candidates.append(cls._close_truncated_json(cleaned))
        if match:
            candidates.append(cls._close_truncated_json(match.group()))

        last_error: json.JSONDecodeError | None = None
        for candidate in candidates:
            try:
                parsed = json.loads(candidate)
                if isinstance(parsed, dict):
                    return parsed
            except json.JSONDecodeError as exc:
                last_error = exc
                continue

        detail = str(last_error) if last_error else "no JSON object found"
        raise ValueError(
            f"Could not parse JSON from response: {detail}"
        ) from last_error

    # ------------------------------------------------------------------
    # Job status helpers
    # ------------------------------------------------------------------

    async def _ensure_not_cancelled(self, job: GenerationJob) -> None:
        """Reload job status and abort if the user cancelled the run."""
        refreshed = await self._gen_repo.get_by_id(job.id, job.organization_id)
        job.status = refreshed.status
        if refreshed.status == GenerationJobStatus.CANCELLED:
            raise GenerationCancelledError()

    async def _mark_cancelled(self, job: GenerationJob) -> None:
        job.status = GenerationJobStatus.CANCELLED
        job.completed_at = datetime.now(UTC)
        if not job.error_message:
            job.error_message = "Cancelled by user"
        await self._db.flush()

    async def _mark_running(self, job: GenerationJob) -> None:
        job.status = GenerationJobStatus.RUNNING
        job.started_at = datetime.now(UTC)
        await self._db.flush()

    async def _mark_completed(self, job: GenerationJob, artifact: Artifact) -> None:
        job.status = GenerationJobStatus.COMPLETED
        job.output_artifact_id = artifact.id
        job.completed_at = datetime.now(UTC)
        await self._db.flush()

    async def _mark_failed(self, job: GenerationJob, error: str) -> None:
        job.status = GenerationJobStatus.FAILED
        job.error_message = error[:2000]  # truncate for DB column
        job.completed_at = datetime.now(UTC)
        try:
            await self._db.flush()
        except Exception:
            pass
